pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot\-preview\[bot\]
      - status-success=continuous-integration/travis-ci/pr
      - "#files=2"
      - files=package-lock.json
      - files=package.json
    actions:
      merge:
        method: merge
